### ISSUE TITLE
Would it be unsafe to lower the iteration number of dlnproof?

### ISSUE THREAD

**Issue by rayhopf** [ChainSafe/tss-lib#9]
Official iteration is 128, you changed it to 12. Would it be unsafe to lower the iteration number?

https://github.com/ChainSafe/tss-lib/blob/chainbridge/crypto/dlnp/proof.go#L22

@kalambet @wemeetagain @empea-careercriminal @edwardmack @morrigan

**Comment by nulltea** [comment]
@rayhopf thank you for the heads up! Looks like it was changed for the thorchain branch for some reason. Can see that the official thorchain fork uses 128 https://gitlab.com/thorchain/tss/tss-lib/-/blob/master/crypto/dlnp/proof.go#L22.

Fixed in https://github.com/ChainSafe/tss-lib/commit/8997bd261bfd293ad84434786d0224ea0e2e78bc

We are archiving this fork in favor of https://github.com/ChainSafe/threshlib which is based on https://eprint.iacr.org/2021/060 and uses Schnorr proofs instead.
